### ISSUE TITLE
Spaces are not a character

### ISSUE THREAD

**Issue by toby-bro** [jrpie/Launcher#29]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I type a space and it is not used in the search : play store has a space so to open it I would type `y `

**Describe the solution you'd like**
Just add it back in the search mechanism

**Describe alternatives you've considered**

**Additional info**
Add any other info, comments or screenshots about the feature request here.

**Comment by jrpie** [comment]
On the other hand, I find it hard to memorize whether an app name is spelled with or without a space.

I see two possibilities for this

(a) add a setting
(b) if the search query contains a space, spaces are respected, otherwise they are disregarded. Something similar could be done for `_`, `-` and perhaps case sensitivity.
