### ISSUE TITLE
Rotating screen in settings makes buttons unavailable

### ISSUE THREAD

**Issue by toby-bro** [jrpie/Launcher#36]
**Describe the bug**
In the meta tab, once the screen is rotated, nearly all the buttons are off screen...

**Expected behavior**
Be able to scroll on the buttons.
The same could be applicable on the first tab of the settings which get highly impracticable when the screen is rotated.
Maybe it could be a solution not to take screen rotation into account when in the settings.

**Comment by jrpie** [comment]
thanks for reporting! Could you please send a screenshot?

**Comment by jrpie** [comment]
Just fired up an emulator with a small screen.
![image](https://github.com/user-attachments/assets/e62a0b33-03be-4878-80d2-a6f8ece8d850)
Indeed that is not looking very good.

I don't really know what to do about this. Making the entire screen scrollable doesn't seem to be a good solution since nested scrollable views are generally a bad idea. Hiding the buttons on small screens might be an option, they don't seem to be too useful anyway (but that is somewhat inconsistent).

**Comment by jrpie** [comment]
The "view all apps" button seems kind of pointless to me, maybe I should remove it entirely. (I access settings through all apps most of the time anyway)

**Comment by toby-bro** [comment]
indeed deleting the view all app can be an option, 
install apps can also be hidden in this layout, 

On the other hand for the Meta tab : it could be an idea to make it scrollable, in landscape it will be too small so scrollable, and in portait mode it will be small enough not to be scrollable

**Comment by jrpie** [comment]
yes, meta shoud definitely be scrollable

**Comment by jrpie** [comment]
[Screen_recording_20240914_132824.webm](https://github.com/user-attachments/assets/ebf989d7-39e7-466e-9b3d-fea1ecdf1cfa)
