### ISSUE TITLE
[feature] Hide apps present in gestures

### ISSUE THREAD

**Issue by apprehensions** [jrpie/Launcher#67]
#  Please describe the problem to be solved

Apps which have their own gestures are present in the 'All Apps' menu

#  Describe the solution you would suggest

An option to hide apps that already have their own gestures

#  Describe alternative solutions you've considered

Manually hiding the apps

**Comment by jrpie** [comment]
Thanks for the suggestion! Sounds like a useful feature to me!

Some things to discuss:
* Should apps bound to gestures be shown in "settings > hidden apps"?
* In particular: should we allow users to manually unhide an app that is hidden because it is bound to a gesture?
   
I see sevaral ways to implement this:
(a) quick & dirty hack: When the option is set an an app is bound to a gesture hide the app (in the same ways as if the user had manually chosen to hide it). When an app is removed (and not bound to any other gesture) unhide it.
This has some obvious problems, e.g. hide an app manually, bind it to a gesture, remove it from a gesture => it will now be visible again.
(b) manage "hidden explicitly" and "hidden because bound to gesture" as completely different categories. This might be confusing, as there are now different notions of "hidden". In particular, apps bound to a gesture would not show up as hidden apps.
(c) store the reason why an app is hidden or visible

**Comment by apprehensions** [comment]
Consider an implementation similar to this: An option to not show (different from hide) apps which already have their own gestures, since those apps, simply have a different way of being launched, compared to the apps present in the 'All Apps' menu, which also have their own way of being launched.

> should we allow users to manually unhide an app that is hidden because it is bound to a gesture?

For these types of users, having the single option of hiding all apps will not be enough, since these people most likely will be more pleased with manually selecting which apps are explicitly hidden.

**Comment by jrpie** [comment]
Implemented ind acbcef5.
Note that this might not work correctly with apps which were bound using an old version of the app - especially for default apps (those are sometimes stored incompletely)
